/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.sdyc.jise;  
@SuppressWarnings("all")
/** AomenFoodReview */
@org.apache.avro.specific.AvroGenerated
public class AomenFoodReview extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2793090237884696915L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AomenFoodReview\",\"namespace\":\"com.sdyc.jise\",\"doc\":\"AomenFoodReview\",\"fields\":[{\"name\":\"shopId\",\"type\":[\"null\",\"string\"],\"doc\":\"店铺id\"},{\"name\":\"shopName\",\"type\":[\"null\",\"string\"],\"doc\":\"店铺名称\"},{\"name\":\"shopImg\",\"type\":[\"null\",\"string\"],\"doc\":\"店铺图片\"},{\"name\":\"shopScore\",\"type\":[\"null\",\"double\"],\"doc\":\"店铺评分\"},{\"name\":\"cntReplied\",\"type\":[\"null\",\"int\"],\"doc\":\"店铺评论数\"},{\"name\":\"createdAt\",\"type\":[\"null\",\"string\"],\"doc\":\"评论时间\"},{\"name\":\"postId\",\"type\":[\"null\",\"string\"],\"doc\":\"评论id\"},{\"name\":\"postTitle\",\"type\":[\"null\",\"string\"],\"doc\":\"评论标题\"},{\"name\":\"postContentText\",\"type\":[\"null\",\"string\"],\"doc\":\"评论内容\"},{\"name\":\"userId\",\"type\":[\"null\",\"string\"],\"doc\":\"评论用户id\"},{\"name\":\"userName\",\"type\":[\"null\",\"string\"],\"doc\":\"评论用户昵称\"},{\"name\":\"userImg\",\"type\":[\"null\",\"string\"],\"doc\":\"评论用户头像\"},{\"name\":\"postUrl\",\"type\":[\"null\",\"string\"],\"doc\":\"帖子链接地址\"},{\"name\":\"reScore\",\"type\":[\"null\",\"double\"],\"doc\":\"评论分数\"},{\"name\":\"mediaName\",\"type\":[\"null\",\"string\"],\"doc\":\"媒体名称\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** 店铺id */
  @Deprecated public java.lang.CharSequence shopId;
  /** 店铺名称 */
  @Deprecated public java.lang.CharSequence shopName;
  /** 店铺图片 */
  @Deprecated public java.lang.CharSequence shopImg;
  /** 店铺评分 */
  @Deprecated public java.lang.Double shopScore;
  /** 店铺评论数 */
  @Deprecated public java.lang.Integer cntReplied;
  /** 评论时间 */
  @Deprecated public java.lang.CharSequence createdAt;
  /** 评论id */
  @Deprecated public java.lang.CharSequence postId;
  /** 评论标题 */
  @Deprecated public java.lang.CharSequence postTitle;
  /** 评论内容 */
  @Deprecated public java.lang.CharSequence postContentText;
  /** 评论用户id */
  @Deprecated public java.lang.CharSequence userId;
  /** 评论用户昵称 */
  @Deprecated public java.lang.CharSequence userName;
  /** 评论用户头像 */
  @Deprecated public java.lang.CharSequence userImg;
  /** 帖子链接地址 */
  @Deprecated public java.lang.CharSequence postUrl;
  /** 评论分数 */
  @Deprecated public java.lang.Double reScore;
  /** 媒体名称 */
  @Deprecated public java.lang.CharSequence mediaName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AomenFoodReview() {}

  /**
   * All-args constructor.
   * @param shopId 店铺id
   * @param shopName 店铺名称
   * @param shopImg 店铺图片
   * @param shopScore 店铺评分
   * @param cntReplied 店铺评论数
   * @param createdAt 评论时间
   * @param postId 评论id
   * @param postTitle 评论标题
   * @param postContentText 评论内容
   * @param userId 评论用户id
   * @param userName 评论用户昵称
   * @param userImg 评论用户头像
   * @param postUrl 帖子链接地址
   * @param reScore 评论分数
   * @param mediaName 媒体名称
   */
  public AomenFoodReview(java.lang.CharSequence shopId, java.lang.CharSequence shopName, java.lang.CharSequence shopImg, java.lang.Double shopScore, java.lang.Integer cntReplied, java.lang.CharSequence createdAt, java.lang.CharSequence postId, java.lang.CharSequence postTitle, java.lang.CharSequence postContentText, java.lang.CharSequence userId, java.lang.CharSequence userName, java.lang.CharSequence userImg, java.lang.CharSequence postUrl, java.lang.Double reScore, java.lang.CharSequence mediaName) {
    this.shopId = shopId;
    this.shopName = shopName;
    this.shopImg = shopImg;
    this.shopScore = shopScore;
    this.cntReplied = cntReplied;
    this.createdAt = createdAt;
    this.postId = postId;
    this.postTitle = postTitle;
    this.postContentText = postContentText;
    this.userId = userId;
    this.userName = userName;
    this.userImg = userImg;
    this.postUrl = postUrl;
    this.reScore = reScore;
    this.mediaName = mediaName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shopId;
    case 1: return shopName;
    case 2: return shopImg;
    case 3: return shopScore;
    case 4: return cntReplied;
    case 5: return createdAt;
    case 6: return postId;
    case 7: return postTitle;
    case 8: return postContentText;
    case 9: return userId;
    case 10: return userName;
    case 11: return userImg;
    case 12: return postUrl;
    case 13: return reScore;
    case 14: return mediaName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shopId = (java.lang.CharSequence)value$; break;
    case 1: shopName = (java.lang.CharSequence)value$; break;
    case 2: shopImg = (java.lang.CharSequence)value$; break;
    case 3: shopScore = (java.lang.Double)value$; break;
    case 4: cntReplied = (java.lang.Integer)value$; break;
    case 5: createdAt = (java.lang.CharSequence)value$; break;
    case 6: postId = (java.lang.CharSequence)value$; break;
    case 7: postTitle = (java.lang.CharSequence)value$; break;
    case 8: postContentText = (java.lang.CharSequence)value$; break;
    case 9: userId = (java.lang.CharSequence)value$; break;
    case 10: userName = (java.lang.CharSequence)value$; break;
    case 11: userImg = (java.lang.CharSequence)value$; break;
    case 12: postUrl = (java.lang.CharSequence)value$; break;
    case 13: reScore = (java.lang.Double)value$; break;
    case 14: mediaName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'shopId' field.
   * @return 店铺id
   */
  public java.lang.CharSequence getShopId() {
    return shopId;
  }

  /**
   * Sets the value of the 'shopId' field.
   * 店铺id
   * @param value the value to set.
   */
  public void setShopId(java.lang.CharSequence value) {
    this.shopId = value;
  }

  /**
   * Gets the value of the 'shopName' field.
   * @return 店铺名称
   */
  public java.lang.CharSequence getShopName() {
    return shopName;
  }

  /**
   * Sets the value of the 'shopName' field.
   * 店铺名称
   * @param value the value to set.
   */
  public void setShopName(java.lang.CharSequence value) {
    this.shopName = value;
  }

  /**
   * Gets the value of the 'shopImg' field.
   * @return 店铺图片
   */
  public java.lang.CharSequence getShopImg() {
    return shopImg;
  }

  /**
   * Sets the value of the 'shopImg' field.
   * 店铺图片
   * @param value the value to set.
   */
  public void setShopImg(java.lang.CharSequence value) {
    this.shopImg = value;
  }

  /**
   * Gets the value of the 'shopScore' field.
   * @return 店铺评分
   */
  public java.lang.Double getShopScore() {
    return shopScore;
  }

  /**
   * Sets the value of the 'shopScore' field.
   * 店铺评分
   * @param value the value to set.
   */
  public void setShopScore(java.lang.Double value) {
    this.shopScore = value;
  }

  /**
   * Gets the value of the 'cntReplied' field.
   * @return 店铺评论数
   */
  public java.lang.Integer getCntReplied() {
    return cntReplied;
  }

  /**
   * Sets the value of the 'cntReplied' field.
   * 店铺评论数
   * @param value the value to set.
   */
  public void setCntReplied(java.lang.Integer value) {
    this.cntReplied = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return 评论时间
   */
  public java.lang.CharSequence getCreatedAt() {
    return createdAt;
  }

  /**
   * Sets the value of the 'createdAt' field.
   * 评论时间
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.CharSequence value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'postId' field.
   * @return 评论id
   */
  public java.lang.CharSequence getPostId() {
    return postId;
  }

  /**
   * Sets the value of the 'postId' field.
   * 评论id
   * @param value the value to set.
   */
  public void setPostId(java.lang.CharSequence value) {
    this.postId = value;
  }

  /**
   * Gets the value of the 'postTitle' field.
   * @return 评论标题
   */
  public java.lang.CharSequence getPostTitle() {
    return postTitle;
  }

  /**
   * Sets the value of the 'postTitle' field.
   * 评论标题
   * @param value the value to set.
   */
  public void setPostTitle(java.lang.CharSequence value) {
    this.postTitle = value;
  }

  /**
   * Gets the value of the 'postContentText' field.
   * @return 评论内容
   */
  public java.lang.CharSequence getPostContentText() {
    return postContentText;
  }

  /**
   * Sets the value of the 'postContentText' field.
   * 评论内容
   * @param value the value to set.
   */
  public void setPostContentText(java.lang.CharSequence value) {
    this.postContentText = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return 评论用户id
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }

  /**
   * Sets the value of the 'userId' field.
   * 评论用户id
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'userName' field.
   * @return 评论用户昵称
   */
  public java.lang.CharSequence getUserName() {
    return userName;
  }

  /**
   * Sets the value of the 'userName' field.
   * 评论用户昵称
   * @param value the value to set.
   */
  public void setUserName(java.lang.CharSequence value) {
    this.userName = value;
  }

  /**
   * Gets the value of the 'userImg' field.
   * @return 评论用户头像
   */
  public java.lang.CharSequence getUserImg() {
    return userImg;
  }

  /**
   * Sets the value of the 'userImg' field.
   * 评论用户头像
   * @param value the value to set.
   */
  public void setUserImg(java.lang.CharSequence value) {
    this.userImg = value;
  }

  /**
   * Gets the value of the 'postUrl' field.
   * @return 帖子链接地址
   */
  public java.lang.CharSequence getPostUrl() {
    return postUrl;
  }

  /**
   * Sets the value of the 'postUrl' field.
   * 帖子链接地址
   * @param value the value to set.
   */
  public void setPostUrl(java.lang.CharSequence value) {
    this.postUrl = value;
  }

  /**
   * Gets the value of the 'reScore' field.
   * @return 评论分数
   */
  public java.lang.Double getReScore() {
    return reScore;
  }

  /**
   * Sets the value of the 'reScore' field.
   * 评论分数
   * @param value the value to set.
   */
  public void setReScore(java.lang.Double value) {
    this.reScore = value;
  }

  /**
   * Gets the value of the 'mediaName' field.
   * @return 媒体名称
   */
  public java.lang.CharSequence getMediaName() {
    return mediaName;
  }

  /**
   * Sets the value of the 'mediaName' field.
   * 媒体名称
   * @param value the value to set.
   */
  public void setMediaName(java.lang.CharSequence value) {
    this.mediaName = value;
  }

  /**
   * Creates a new AomenFoodReview RecordBuilder.
   * @return A new AomenFoodReview RecordBuilder
   */
  public static com.sdyc.jise.AomenFoodReview.Builder newBuilder() {
    return new com.sdyc.jise.AomenFoodReview.Builder();
  }
  
  /**
   * Creates a new AomenFoodReview RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AomenFoodReview RecordBuilder
   */
  public static com.sdyc.jise.AomenFoodReview.Builder newBuilder(com.sdyc.jise.AomenFoodReview.Builder other) {
    return new com.sdyc.jise.AomenFoodReview.Builder(other);
  }
  
  /**
   * Creates a new AomenFoodReview RecordBuilder by copying an existing AomenFoodReview instance.
   * @param other The existing instance to copy.
   * @return A new AomenFoodReview RecordBuilder
   */
  public static com.sdyc.jise.AomenFoodReview.Builder newBuilder(com.sdyc.jise.AomenFoodReview other) {
    return new com.sdyc.jise.AomenFoodReview.Builder(other);
  }
  
  /**
   * RecordBuilder for AomenFoodReview instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AomenFoodReview>
    implements org.apache.avro.data.RecordBuilder<AomenFoodReview> {

    /** 店铺id */
    private java.lang.CharSequence shopId;
    /** 店铺名称 */
    private java.lang.CharSequence shopName;
    /** 店铺图片 */
    private java.lang.CharSequence shopImg;
    /** 店铺评分 */
    private java.lang.Double shopScore;
    /** 店铺评论数 */
    private java.lang.Integer cntReplied;
    /** 评论时间 */
    private java.lang.CharSequence createdAt;
    /** 评论id */
    private java.lang.CharSequence postId;
    /** 评论标题 */
    private java.lang.CharSequence postTitle;
    /** 评论内容 */
    private java.lang.CharSequence postContentText;
    /** 评论用户id */
    private java.lang.CharSequence userId;
    /** 评论用户昵称 */
    private java.lang.CharSequence userName;
    /** 评论用户头像 */
    private java.lang.CharSequence userImg;
    /** 帖子链接地址 */
    private java.lang.CharSequence postUrl;
    /** 评论分数 */
    private java.lang.Double reScore;
    /** 媒体名称 */
    private java.lang.CharSequence mediaName;

    /** Creates a new Builder */
    private Builder() {
      super(com.sdyc.jise.AomenFoodReview.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sdyc.jise.AomenFoodReview.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shopId)) {
        this.shopId = data().deepCopy(fields()[0].schema(), other.shopId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.shopName)) {
        this.shopName = data().deepCopy(fields()[1].schema(), other.shopName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.shopImg)) {
        this.shopImg = data().deepCopy(fields()[2].schema(), other.shopImg);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.shopScore)) {
        this.shopScore = data().deepCopy(fields()[3].schema(), other.shopScore);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cntReplied)) {
        this.cntReplied = data().deepCopy(fields()[4].schema(), other.cntReplied);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.postId)) {
        this.postId = data().deepCopy(fields()[6].schema(), other.postId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.postTitle)) {
        this.postTitle = data().deepCopy(fields()[7].schema(), other.postTitle);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.postContentText)) {
        this.postContentText = data().deepCopy(fields()[8].schema(), other.postContentText);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.userId)) {
        this.userId = data().deepCopy(fields()[9].schema(), other.userId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.userName)) {
        this.userName = data().deepCopy(fields()[10].schema(), other.userName);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.userImg)) {
        this.userImg = data().deepCopy(fields()[11].schema(), other.userImg);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.postUrl)) {
        this.postUrl = data().deepCopy(fields()[12].schema(), other.postUrl);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.reScore)) {
        this.reScore = data().deepCopy(fields()[13].schema(), other.reScore);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.mediaName)) {
        this.mediaName = data().deepCopy(fields()[14].schema(), other.mediaName);
        fieldSetFlags()[14] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing AomenFoodReview instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sdyc.jise.AomenFoodReview other) {
            super(com.sdyc.jise.AomenFoodReview.SCHEMA$);
      if (isValidValue(fields()[0], other.shopId)) {
        this.shopId = data().deepCopy(fields()[0].schema(), other.shopId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.shopName)) {
        this.shopName = data().deepCopy(fields()[1].schema(), other.shopName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.shopImg)) {
        this.shopImg = data().deepCopy(fields()[2].schema(), other.shopImg);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.shopScore)) {
        this.shopScore = data().deepCopy(fields()[3].schema(), other.shopScore);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cntReplied)) {
        this.cntReplied = data().deepCopy(fields()[4].schema(), other.cntReplied);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.postId)) {
        this.postId = data().deepCopy(fields()[6].schema(), other.postId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.postTitle)) {
        this.postTitle = data().deepCopy(fields()[7].schema(), other.postTitle);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.postContentText)) {
        this.postContentText = data().deepCopy(fields()[8].schema(), other.postContentText);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.userId)) {
        this.userId = data().deepCopy(fields()[9].schema(), other.userId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.userName)) {
        this.userName = data().deepCopy(fields()[10].schema(), other.userName);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.userImg)) {
        this.userImg = data().deepCopy(fields()[11].schema(), other.userImg);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.postUrl)) {
        this.postUrl = data().deepCopy(fields()[12].schema(), other.postUrl);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.reScore)) {
        this.reScore = data().deepCopy(fields()[13].schema(), other.reScore);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.mediaName)) {
        this.mediaName = data().deepCopy(fields()[14].schema(), other.mediaName);
        fieldSetFlags()[14] = true;
      }
    }

    /**
      * Gets the value of the 'shopId' field.
      * 店铺id
      * @return The value.
      */
    public java.lang.CharSequence getShopId() {
      return shopId;
    }

    /**
      * Sets the value of the 'shopId' field.
      * 店铺id
      * @param value The value of 'shopId'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setShopId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.shopId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'shopId' field has been set.
      * 店铺id
      * @return True if the 'shopId' field has been set, false otherwise.
      */
    public boolean hasShopId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shopId' field.
      * 店铺id
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearShopId() {
      shopId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'shopName' field.
      * 店铺名称
      * @return The value.
      */
    public java.lang.CharSequence getShopName() {
      return shopName;
    }

    /**
      * Sets the value of the 'shopName' field.
      * 店铺名称
      * @param value The value of 'shopName'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setShopName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.shopName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'shopName' field has been set.
      * 店铺名称
      * @return True if the 'shopName' field has been set, false otherwise.
      */
    public boolean hasShopName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'shopName' field.
      * 店铺名称
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearShopName() {
      shopName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'shopImg' field.
      * 店铺图片
      * @return The value.
      */
    public java.lang.CharSequence getShopImg() {
      return shopImg;
    }

    /**
      * Sets the value of the 'shopImg' field.
      * 店铺图片
      * @param value The value of 'shopImg'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setShopImg(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.shopImg = value;
      fieldSetFlags()[2] = true;
      return this; 
    }

    /**
      * Checks whether the 'shopImg' field has been set.
      * 店铺图片
      * @return True if the 'shopImg' field has been set, false otherwise.
      */
    public boolean hasShopImg() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'shopImg' field.
      * 店铺图片
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearShopImg() {
      shopImg = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'shopScore' field.
      * 店铺评分
      * @return The value.
      */
    public java.lang.Double getShopScore() {
      return shopScore;
    }

    /**
      * Sets the value of the 'shopScore' field.
      * 店铺评分
      * @param value The value of 'shopScore'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setShopScore(java.lang.Double value) {
      validate(fields()[3], value);
      this.shopScore = value;
      fieldSetFlags()[3] = true;
      return this; 
    }

    /**
      * Checks whether the 'shopScore' field has been set.
      * 店铺评分
      * @return True if the 'shopScore' field has been set, false otherwise.
      */
    public boolean hasShopScore() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'shopScore' field.
      * 店铺评分
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearShopScore() {
      shopScore = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'cntReplied' field.
      * 店铺评论数
      * @return The value.
      */
    public java.lang.Integer getCntReplied() {
      return cntReplied;
    }

    /**
      * Sets the value of the 'cntReplied' field.
      * 店铺评论数
      * @param value The value of 'cntReplied'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setCntReplied(java.lang.Integer value) {
      validate(fields()[4], value);
      this.cntReplied = value;
      fieldSetFlags()[4] = true;
      return this; 
    }

    /**
      * Checks whether the 'cntReplied' field has been set.
      * 店铺评论数
      * @return True if the 'cntReplied' field has been set, false otherwise.
      */
    public boolean hasCntReplied() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'cntReplied' field.
      * 店铺评论数
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearCntReplied() {
      cntReplied = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * 评论时间
      * @return The value.
      */
    public java.lang.CharSequence getCreatedAt() {
      return createdAt;
    }

    /**
      * Sets the value of the 'createdAt' field.
      * 评论时间
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setCreatedAt(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.createdAt = value;
      fieldSetFlags()[5] = true;
      return this; 
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * 评论时间
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * 评论时间
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'postId' field.
      * 评论id
      * @return The value.
      */
    public java.lang.CharSequence getPostId() {
      return postId;
    }

    /**
      * Sets the value of the 'postId' field.
      * 评论id
      * @param value The value of 'postId'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setPostId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.postId = value;
      fieldSetFlags()[6] = true;
      return this; 
    }

    /**
      * Checks whether the 'postId' field has been set.
      * 评论id
      * @return True if the 'postId' field has been set, false otherwise.
      */
    public boolean hasPostId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'postId' field.
      * 评论id
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearPostId() {
      postId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'postTitle' field.
      * 评论标题
      * @return The value.
      */
    public java.lang.CharSequence getPostTitle() {
      return postTitle;
    }

    /**
      * Sets the value of the 'postTitle' field.
      * 评论标题
      * @param value The value of 'postTitle'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setPostTitle(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.postTitle = value;
      fieldSetFlags()[7] = true;
      return this; 
    }

    /**
      * Checks whether the 'postTitle' field has been set.
      * 评论标题
      * @return True if the 'postTitle' field has been set, false otherwise.
      */
    public boolean hasPostTitle() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'postTitle' field.
      * 评论标题
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearPostTitle() {
      postTitle = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'postContentText' field.
      * 评论内容
      * @return The value.
      */
    public java.lang.CharSequence getPostContentText() {
      return postContentText;
    }

    /**
      * Sets the value of the 'postContentText' field.
      * 评论内容
      * @param value The value of 'postContentText'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setPostContentText(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.postContentText = value;
      fieldSetFlags()[8] = true;
      return this; 
    }

    /**
      * Checks whether the 'postContentText' field has been set.
      * 评论内容
      * @return True if the 'postContentText' field has been set, false otherwise.
      */
    public boolean hasPostContentText() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'postContentText' field.
      * 评论内容
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearPostContentText() {
      postContentText = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * 评论用户id
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }

    /**
      * Sets the value of the 'userId' field.
      * 评论用户id
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.userId = value;
      fieldSetFlags()[9] = true;
      return this; 
    }

    /**
      * Checks whether the 'userId' field has been set.
      * 评论用户id
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'userId' field.
      * 评论用户id
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'userName' field.
      * 评论用户昵称
      * @return The value.
      */
    public java.lang.CharSequence getUserName() {
      return userName;
    }

    /**
      * Sets the value of the 'userName' field.
      * 评论用户昵称
      * @param value The value of 'userName'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setUserName(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.userName = value;
      fieldSetFlags()[10] = true;
      return this; 
    }

    /**
      * Checks whether the 'userName' field has been set.
      * 评论用户昵称
      * @return True if the 'userName' field has been set, false otherwise.
      */
    public boolean hasUserName() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'userName' field.
      * 评论用户昵称
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearUserName() {
      userName = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'userImg' field.
      * 评论用户头像
      * @return The value.
      */
    public java.lang.CharSequence getUserImg() {
      return userImg;
    }

    /**
      * Sets the value of the 'userImg' field.
      * 评论用户头像
      * @param value The value of 'userImg'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setUserImg(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.userImg = value;
      fieldSetFlags()[11] = true;
      return this; 
    }

    /**
      * Checks whether the 'userImg' field has been set.
      * 评论用户头像
      * @return True if the 'userImg' field has been set, false otherwise.
      */
    public boolean hasUserImg() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'userImg' field.
      * 评论用户头像
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearUserImg() {
      userImg = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'postUrl' field.
      * 帖子链接地址
      * @return The value.
      */
    public java.lang.CharSequence getPostUrl() {
      return postUrl;
    }

    /**
      * Sets the value of the 'postUrl' field.
      * 帖子链接地址
      * @param value The value of 'postUrl'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setPostUrl(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.postUrl = value;
      fieldSetFlags()[12] = true;
      return this; 
    }

    /**
      * Checks whether the 'postUrl' field has been set.
      * 帖子链接地址
      * @return True if the 'postUrl' field has been set, false otherwise.
      */
    public boolean hasPostUrl() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'postUrl' field.
      * 帖子链接地址
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearPostUrl() {
      postUrl = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'reScore' field.
      * 评论分数
      * @return The value.
      */
    public java.lang.Double getReScore() {
      return reScore;
    }

    /**
      * Sets the value of the 'reScore' field.
      * 评论分数
      * @param value The value of 'reScore'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setReScore(java.lang.Double value) {
      validate(fields()[13], value);
      this.reScore = value;
      fieldSetFlags()[13] = true;
      return this; 
    }

    /**
      * Checks whether the 'reScore' field has been set.
      * 评论分数
      * @return True if the 'reScore' field has been set, false otherwise.
      */
    public boolean hasReScore() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'reScore' field.
      * 评论分数
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearReScore() {
      reScore = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'mediaName' field.
      * 媒体名称
      * @return The value.
      */
    public java.lang.CharSequence getMediaName() {
      return mediaName;
    }

    /**
      * Sets the value of the 'mediaName' field.
      * 媒体名称
      * @param value The value of 'mediaName'.
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder setMediaName(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.mediaName = value;
      fieldSetFlags()[14] = true;
      return this; 
    }

    /**
      * Checks whether the 'mediaName' field has been set.
      * 媒体名称
      * @return True if the 'mediaName' field has been set, false otherwise.
      */
    public boolean hasMediaName() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'mediaName' field.
      * 媒体名称
      * @return This builder.
      */
    public com.sdyc.jise.AomenFoodReview.Builder clearMediaName() {
      mediaName = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    @Override
    public AomenFoodReview build() {
      try {
        AomenFoodReview record = new AomenFoodReview();
        record.shopId = fieldSetFlags()[0] ? this.shopId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.shopName = fieldSetFlags()[1] ? this.shopName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.shopImg = fieldSetFlags()[2] ? this.shopImg : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.shopScore = fieldSetFlags()[3] ? this.shopScore : (java.lang.Double) defaultValue(fields()[3]);
        record.cntReplied = fieldSetFlags()[4] ? this.cntReplied : (java.lang.Integer) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.postId = fieldSetFlags()[6] ? this.postId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.postTitle = fieldSetFlags()[7] ? this.postTitle : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.postContentText = fieldSetFlags()[8] ? this.postContentText : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.userId = fieldSetFlags()[9] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.userName = fieldSetFlags()[10] ? this.userName : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.userImg = fieldSetFlags()[11] ? this.userImg : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.postUrl = fieldSetFlags()[12] ? this.postUrl : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.reScore = fieldSetFlags()[13] ? this.reScore : (java.lang.Double) defaultValue(fields()[13]);
        record.mediaName = fieldSetFlags()[14] ? this.mediaName : (java.lang.CharSequence) defaultValue(fields()[14]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
